import type { Metadata } from 'next';
import {  Roboto } from 'next/font/google';
import { Providers } from './providers';
import './globals.css';
import Header from '@/components/header/header';


const roboto = Roboto({ weight: '400', subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Pasal',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={roboto.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
